package com.lizhi.mybatis.mapper;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.lizhi.bean.TFile;
import com.lizhi.bean.TFileExample;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    long countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Sun Jul 08 21:07:30 CST 2018
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);
}